"""
seed.py — SetupMaker
====================
Popula o banco com 80 peças (10 por categoria) com imagens individuais.
Execute via: flask seed
"""
from app.extensions import db
from app.models.produto import Categoria, Produto
from app.models.loja import Loja, Preco
from app.models.user import User


def run():
    # ── Categorias ────────────────────────────────────────────────
    cats = [
        Categoria(nome="Processador",    slug="cpu"),
        Categoria(nome="Placa de Vídeo", slug="gpu"),
        Categoria(nome="Memória RAM",    slug="ram"),
        Categoria(nome="Placa-Mãe",      slug="motherboard"),
        Categoria(nome="Armazenamento",  slug="storage"),
        Categoria(nome="Fonte",          slug="psu"),
        Categoria(nome="Gabinete",       slug="case"),
        Categoria(nome="Cooler",         slug="cooler"),
    ]
    for c in cats:
        if not Categoria.query.filter_by(slug=c.slug).first():
            db.session.add(c)
    db.session.flush()

    def cat(slug): return Categoria.query.filter_by(slug=slug).first()

    produtos = [

        # ── CPUs ──────────────────────────────────────────────────
        Produto(
            nome="AMD Ryzen 5 5600", marca="AMD",
            categoria_id=cat("cpu").id, socket="AM4",
            consumo_watts=65, desempenho=72,
            frequencia="3.5 GHz (boost 4.4 GHz)",
            descricao="6 núcleos / 12 threads | Socket AM4 | TDP 65W | Cache L3 32MB | Processo 7nm TSMC | Excelente custo-benefício para gaming 1080p/1440p. Compatível com placas B450, B550 e X570.",
            imagem_url="https://down-br.img.susercontent.com/file/br-11134207-7r98o-m3te3k79mat1c6",
        ),
        Produto(
            nome="AMD Ryzen 7 7700X", marca="AMD",
            categoria_id=cat("cpu").id, socket="AM5",
            consumo_watts=105, desempenho=88,
            frequencia="4.5 GHz (boost 5.4 GHz)",
            descricao="8 núcleos / 16 threads | Socket AM5 | TDP 105W | Cache L3 32MB | Processo 5nm TSMC | DDR5 | PCIe 5.0 | Excelente para gaming e multitarefas. Requer cooler dedicado.",
            imagem_url="https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-7-7700x-og.jpg",
        ),
        Produto(
            nome="AMD Ryzen 5 7600X", marca="AMD",
            categoria_id=cat("cpu").id, socket="AM5",
            consumo_watts=105, desempenho=82,
            frequencia="4.7 GHz (boost 5.3 GHz)",
            descricao="6 núcleos / 12 threads | Socket AM5 | TDP 105W | Cache L3 32MB | Processo 5nm | DDR5 | PCIe 5.0 | Melhor CPU 6-core da geração AM5 para gaming.",
            imagem_url="https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-5-7600x-og.jpg",
        ),
        Produto(
            nome="Intel Core i5-13600K", marca="Intel",
            categoria_id=cat("cpu").id, socket="LGA1700",
            consumo_watts=125, desempenho=90,
            frequencia="3.5 GHz (boost 5.1 GHz)",
            descricao="14 núcleos (6P+8E) / 20 threads | Socket LGA1700 | TDP 125W | Cache L3 24MB | DDR4/DDR5 | PCIe 5.0 | Referência em desempenho mid-range, excelente para gaming e criação.",
            imagem_url="https://carrefourbr.vtexassets.com/arquivos/ids/183898109/image-1.jpg?v=638746231793500000",
        ),
        Produto(
            nome="Intel Core i7-14700K", marca="Intel",
            categoria_id=cat("cpu").id, socket="LGA1700",
            consumo_watts=125, desempenho=93,
            frequencia="3.4 GHz (boost 5.6 GHz)",
            descricao="20 núcleos (8P+12E) / 28 threads | Socket LGA1700 | TDP 125W | Cache L3 33MB | DDR4/DDR5 | PCIe 5.0 | Top de linha mid-high Intel, excelente para streaming e multitarefas pesadas.",
            imagem_url="https://images.kabum.com.br/produtos/fotos/sync_mirakl/728921/xlarge/Intel-Core-i7-14700k-14-Ger-20-Nuc-28-Threads-4-3-Ghz-5-6-Ghz-Turbo-Soquete-LGA-1700-Proc-De-Desktop-Desbloqueado-Multi-bx8071514700k_1747224291.jpg",
        ),
        Produto(
            nome="Intel Core i3-12100F", marca="Intel",
            categoria_id=cat("cpu").id, socket="LGA1700",
            consumo_watts=58, desempenho=55,
            frequencia="3.3 GHz (boost 4.3 GHz)",
            descricao="4 núcleos / 8 threads | Socket LGA1700 | TDP 58W | Cache L3 12MB | Sem GPU integrada | Melhor opção entry-level Intel para quem já tem GPU dedicada.",
            imagem_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0mKqCPC47Vs0yhdhiSQ3xump641g4eHtAvQ&s",
        ),
        Produto(
            nome="AMD Ryzen 9 7900X", marca="AMD",
            categoria_id=cat("cpu").id, socket="AM5",
            consumo_watts=170, desempenho=95,
            frequencia="4.7 GHz (boost 5.6 GHz)",
            descricao="12 núcleos / 24 threads | Socket AM5 | TDP 170W | Cache L3 64MB | Processo 5nm | DDR5 | PCIe 5.0 | Powerhouse para workstations e gaming de alto nível.",
            imagem_url="https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-9-7900x-og.jpg",
        ),
        Produto(
            nome="AMD Ryzen 5 5500", marca="AMD",
            categoria_id=cat("cpu").id, socket="AM4",
            consumo_watts=65, desempenho=65,
            frequencia="3.6 GHz (boost 4.2 GHz)",
            descricao="6 núcleos / 12 threads | Socket AM4 | TDP 65W | Cache L3 16MB | Processo 7nm | Ótima opção de custo-benefício para upgrades em plataforma AM4.",
            imagem_url="https://ae01.alicdn.com/kf/Sa03f288f3a5541e8bc5020eb59fed5abN.jpg",
        ),
        Produto(
            nome="Intel Core i9-14900K", marca="Intel",
            categoria_id=cat("cpu").id, socket="LGA1700",
            consumo_watts=125, desempenho=99,
            frequencia="3.2 GHz (boost 6.0 GHz)",
            descricao="24 núcleos (8P+16E) / 32 threads | Socket LGA1700 | TDP 125W (253W PBP) | Cache L3 36MB | DDR5 | PCIe 5.0 | CPU flagship Intel — máximo desempenho single e multi-core do mercado.",
            imagem_url="https://m.media-amazon.com/images/I/61ujd7RN-3L.jpg",
        ),
        Produto(
            nome="AMD Ryzen 7 5700X", marca="AMD",
            categoria_id=cat("cpu").id, socket="AM4",
            consumo_watts=65, desempenho=78,
            frequencia="3.4 GHz (boost 4.6 GHz)",
            descricao="8 núcleos / 16 threads | Socket AM4 | TDP 65W | Cache L3 32MB | Processo 7nm | Excelente escolha para quem quer 8 cores na plataforma AM4 econômica.",
            imagem_url="https://s2-techtudo.glbimg.com/9zMiAo_VadvqxNMGVBNaXTGzCE4=/filters:format(jpeg)/https://i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2022/i/P/mEdGq7RdK5KfB7oSEtow/amd-ryzen-7.jpg",
        ),

        # ── GPUs ──────────────────────────────────────────────────
        Produto(
            nome="NVIDIA RTX 5090", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=575, desempenho=100, capacidade="32GB GDDR7",
            descricao="32GB GDDR7 | Bus 512-bit | 21.760 CUDA Cores | Arquitetura Blackwell | PCIe 5.0 | GPU mais poderosa do mundo. 4K/8K com ray tracing máximo, IA e workstation.",
            imagem_url="https://www.nvidia.com/content/nvidiaGDC/br/pt_BR/geforce/graphics-cards/50-series/rtx-5090/_jcr_content/root/responsivegrid/nv_modalcontainer_1683966542/nv_image.coreimg.100.1070.jpeg/1736094519375/geforce-rtx-5090-gallery-shot-2-ari.jpeg",
        ),
        Produto(
            nome="NVIDIA RTX 5080", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=360, desempenho=94, capacidade="16GB GDDR7",
            descricao="16GB GDDR7 | Bus 256-bit | 10.752 CUDA Cores | Arquitetura Blackwell | PCIe 5.0 | DLSS 4 | Flagship para a maioria dos jogadores — 4K Ultra sem limitações.",
            imagem_url="https://s2-techtudo.glbimg.com/NDWegcJ_AioyjH3AqsIpdy1L9hE=/filters:format(jpeg)/https://i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2025/t/W/7dAnivRdGTkl6S9wBbyw/geforce-rtx-5080-key-visual.jpg",
        ),
        Produto(
            nome="NVIDIA RTX 5070 Ti", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=300, desempenho=88, capacidade="16GB GDDR7",
            descricao="16GB GDDR7 | Bus 256-bit | 8.960 CUDA Cores | Arquitetura Blackwell | PCIe 5.0 | DLSS 4 | Excelente para 1440p/4K — desempenho próximo à RTX 4090 anterior.",
            imagem_url="https://d1q3zw97enxzq2.cloudfront.net/images/ASUS_PRIME_GeForce_RTX_5070_Ti.width-1000.format-webp.webp",
        ),
        Produto(
            nome="NVIDIA RTX 5060 Ti", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=180, desempenho=78, capacidade="16GB GDDR7",
            descricao="16GB GDDR7 | Bus 128-bit | 4.608 CUDA Cores | Arquitetura Blackwell | DLSS 4 | Frame Generation | Melhor custo-benefício geração Blackwell — domina o 1080p e bom em 1440p.",
            imagem_url="https://cdn.videocardz.com/1/2025/04/MSI-RTX-5060.jpg",
        ),
        Produto(
            nome="NVIDIA RTX 4070", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=200, desempenho=85, capacidade="12GB GDDR6X",
            descricao="12GB GDDR6X | Bus 192-bit | 5.888 CUDA Cores | Arquitetura Ada Lovelace | PCIe 4.0 | DLSS 3 | Ótima GPU para 1440p High/Ultra. Silenciosa e eficiente.",
            imagem_url="https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/graphic-cards/40-series/rtx-4070-4070ti/geforce-rtx-4070-super-og-1200x630.jpg",
        ),
        Produto(
            nome="NVIDIA RTX 4060", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=115, desempenho=72, capacidade="8GB GDDR6",
            descricao="8GB GDDR6 | Bus 128-bit | 3.072 CUDA Cores | Arquitetura Ada Lovelace | DLSS 3 | Frame Generation | Referência 1080p — baixo consumo e silenciosa.",
            imagem_url="https://s2-techtudo.glbimg.com/P34uTrH-Qk6_Yn8Ux9-C6aX7j4s=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2023/3/l/JzjLLhQf64MQw9OW9WuA/4060.png",
        ),
        Produto(
            nome="NVIDIA RTX 3060 12GB", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=170, desempenho=66, capacidade="12GB GDDR6",
            descricao="12GB GDDR6 | Bus 192-bit | 3.584 CUDA Cores | Arquitetura Ampere | PCIe 4.0 | DLSS 2 | Muito VRAM para o preço — ótima para 1080p Ultra e alguns jogos 1440p.",
            imagem_url="https://images.nvidia.com/aem-dam/Solutions/geforce/ampere/rtx-3060-ti/geforce-rtx-3060-ti-product-gallery-full-screen-3840-1-bl.jpg",
        ),
        Produto(
            nome="AMD Radeon RX 7800 XT", marca="AMD",
            categoria_id=cat("gpu").id,
            consumo_watts=263, desempenho=84, capacidade="16GB GDDR6",
            descricao="16GB GDDR6 | Bus 256-bit | 3.840 Stream Processors | Arquitetura RDNA 3 | PCIe 4.0 | FSR 3 | Rival direta da RTX 4070 com mais VRAM — excelente para 1440p.",
            imagem_url="https://t.ctcdn.com.br/CIT7CEI-QAoOeXnvoGQC243J1UM=/640x360/smart/i1075825.png",
        ),
        Produto(
            nome="AMD Radeon RX 7600", marca="AMD",
            categoria_id=cat("gpu").id,
            consumo_watts=165, desempenho=68, capacidade="8GB GDDR6",
            descricao="8GB GDDR6 | Bus 128-bit | 2.048 Stream Processors | Arquitetura RDNA 3 | PCIe 4.0 | FSR 3 | Opção sólida para 1080p com preço competitivo frente à RTX 4060.",
            imagem_url="https://www.notebookcheck.info/fileadmin/Notebooks/News/_nc3/readeonlaunchheader.jpg",
        ),
        Produto(
            nome="NVIDIA RTX 3050", marca="NVIDIA",
            categoria_id=cat("gpu").id,
            consumo_watts=130, desempenho=55, capacidade="8GB GDDR6",
            descricao="8GB GDDR6 | Bus 128-bit | 2.560 CUDA Cores | Arquitetura Ampere | PCIe 4.0 | DLSS 2 | Entry-level com ray tracing e DLSS — boa opção para 1080p médio/alto.",
            imagem_url="https://dlcdnwebimgs.asus.com/files/media/a4efa7c6-a5d6-4e48-aeec-7fe44b7821c1/v1/img/kv.jpg",
        ),

        # ── RAM ───────────────────────────────────────────────────
        Produto(
            nome="Kingston FURY Beast 32GB DDR5 6000MHz", marca="Kingston",
            categoria_id=cat("ram").id, tipo_ram="DDR5",
            frequencia="6000MHz", capacidade="32GB (2x16GB)", consumo_watts=5,
            descricao="32GB (2x16GB) | DDR5-6000 | CL36 | 1.35V | XMP 3.0 / EXPO | Dissipador de alumínio baixo perfil | Ideal para plataformas AM5 e Intel 13/14ªG.",
            imagem_url="https://media.kingston.com/kingston/key-features/ktc-keyfeatures-memory-beast-ddr5-7-lg.jpg",
        ),
        Produto(
            nome="Corsair Vengeance 32GB DDR5 5600MHz", marca="Corsair",
            categoria_id=cat("ram").id, tipo_ram="DDR5",
            frequencia="5600MHz", capacidade="32GB (2x16GB)", consumo_watts=5,
            descricao="32GB (2x16GB) | DDR5-5600 | CL36 | 1.25V | Intel XMP 3.0 | Dissipador de alumínio anodizado | Ótima relação frequência/latência para plataforma Intel DDR5.",
            imagem_url="https://img.evetech.co.za/repository/ProductImages/corsair-vengeance-32gb-5600mhz-ddr5-c40-black-memory-OG-image-1200px-v01.webp",
        ),
        Produto(
            nome="G.Skill Trident Z5 32GB DDR5 6400MHz", marca="G.Skill",
            categoria_id=cat("ram").id, tipo_ram="DDR5",
            frequencia="6400MHz", capacidade="32GB (2x16GB)", consumo_watts=6,
            descricao="32GB (2x16GB) | DDR5-6400 | CL32 | 1.40V | XMP 3.0 | EXPO | Dissipador dual-tone RGB | Memória premium para enthusiasts — frequência e latências de ponta.",
            imagem_url="https://http2.mlstatic.com/D_NQ_NP_758580-CBT98848089515_112025-O-desktop-gskill-trident-z5-neo-rgb-ddr5-32gb-6000mts.webp",
        ),
        Produto(
            nome="Kingston FURY Beast 16GB DDR4 3200MHz", marca="Kingston",
            categoria_id=cat("ram").id, tipo_ram="DDR4",
            frequencia="3200MHz", capacidade="16GB (2x8GB)", consumo_watts=3,
            descricao="16GB (2x8GB) | DDR4-3200 | CL16 | 1.35V | Intel XMP 2.0 | Sem RGB, perfil baixo | Memória confiável e de custo acessível para builds AM4 e LGA1700 DDR4.",
            imagem_url="https://images.tcdn.com.br/img/img_prod/1040701/memoria_ddr4_16gb_3200mhz_kingston_fury_beast_preto_kf432c16bb_16_3807_1_43e1a3c2f36d47e87abcd526be0eb86a.png",
        ),
        Produto(
            nome="Corsair Vengeance LPX 16GB DDR4 3600MHz", marca="Corsair",
            categoria_id=cat("ram").id, tipo_ram="DDR4",
            frequencia="3600MHz", capacidade="16GB (2x8GB)", consumo_watts=3,
            descricao="16GB (2x8GB) | DDR4-3600 | CL18 | 1.35V | Intel XMP 2.0 | Perfil baixo (34mm) | Frequência ideal para Ryzen AM4 — sweet spot de desempenho e preço.",
            imagem_url="https://m.media-amazon.com/images/S/aplus-media-library-service-media/d1774a02-4f82-4cab-9e66-3c046101081b.__CR0,0,970,300_PT0_SX970_V1___.png",
        ),
        Produto(
            nome="G.Skill Ripjaws V 32GB DDR4 3600MHz", marca="G.Skill",
            categoria_id=cat("ram").id, tipo_ram="DDR4",
            frequencia="3600MHz", capacidade="32GB (2x16GB)", consumo_watts=5,
            descricao="32GB (2x16GB) | DDR4-3600 | CL16 | 1.35V | Intel XMP 2.0 | Dissipador de alumínio colorido | 32GB DDR4 de alta frequência — ideal para produtividade e gaming.",
            imagem_url="https://a-static.mlcdn.com.br/420x420/memoria-ram-g-skill-ripjaws-v-ddr4-32gb-2x16gb-3600mhz/nocnocestadosunidos/buybox-cpb07z45xb3g/23ad04ad2433c89b09f1f61f68b61630.jpeg",
        ),
        Produto(
            nome="Corsair Vengeance RGB Pro 16GB DDR4 3200MHz", marca="Corsair",
            categoria_id=cat("ram").id, tipo_ram="DDR4",
            frequencia="3200MHz", capacidade="16GB (2x8GB)", consumo_watts=4,
            descricao="16GB (2x8GB) | DDR4-3200 | CL16 | 1.35V | Intel XMP 2.0 | RGB individual por LEDs | Memória com iluminação RGB caprichada — ótima para builds com janela.",
            imagem_url="https://img.terabyteshop.com.br/archive/3029354591/HTML%20VENGEANCE%20RGB%20PRO%20SL%2002.png",
        ),
        Produto(
            nome="XPG Lancer 32GB DDR5 6000MHz", marca="XPG",
            categoria_id=cat("ram").id, tipo_ram="DDR5",
            frequencia="6000MHz", capacidade="32GB (2x16GB)", consumo_watts=5,
            descricao="32GB (2x16GB) | DDR5-6000 | CL30 | 1.35V | XMP 3.0 / EXPO | RGB | DDR5 de alta performance com suporte nativo a AMD EXPO e Intel XMP.",
            imagem_url="https://t.ctcdn.com.br/72ou5jiqR0JJCTmKb95VfHuY0cU=/640x360/smart/i1039859.png",
        ),
        Produto(
            nome="Kingston Fury Renegade 32GB DDR5 7200MHz", marca="Kingston",
            categoria_id=cat("ram").id, tipo_ram="DDR5",
            frequencia="7200MHz", capacidade="32GB (2x16GB)", consumo_watts=7,
            descricao="32GB (2x16GB) | DDR5-7200 | CL38 | 1.45V | Intel XMP 3.0 | RGB | Dissipador thermal pad | Top de linha DDR5 — para enthusiasts que querem o máximo em frequência.",
            imagem_url="https://m.media-amazon.com/images/I/61eVFYEyD0L._AC_UF894,1000_QL80_.jpg",
        ),
        Produto(
            nome="Crucial 16GB DDR5 4800MHz", marca="Crucial",
            categoria_id=cat("ram").id, tipo_ram="DDR5",
            frequencia="4800MHz", capacidade="16GB (1x16GB)", consumo_watts=4,
            descricao="16GB (1x16GB) | DDR5-4800 | CL40 | 1.1V | Sem XMP (JEDEC nativo) | Perfil baixo sem dissipador | DDR5 de entrada com excelente compatibilidade.",
            imagem_url="https://m.media-amazon.com/images/I/51TyJr5-bBL._AC_UF1000,1000_QL80_.jpg",
        ),

        # ── Placas-Mãe ────────────────────────────────────────────
        Produto(
            nome="ASUS TUF Gaming B650-Plus WiFi", marca="ASUS",
            categoria_id=cat("motherboard").id, socket="AM5", tipo_ram="DDR5",
            consumo_watts=40,
            descricao="Socket AM5 | DDR5 (4x DIMM, até 128GB) | WiFi 6 | Bluetooth 5.3 | PCIe 5.0 x16 | 2x M.2 NVMe | USB 3.2 Gen 2 | ATX | Excelente custo-benefício para plataforma Ryzen 7000.",
            imagem_url="https://dlcdnwebimgs.asus.com/files/media/7f358aac-d2d6-4dd0-8fba-dea85469a22e/V1/img/performance/fan.jpg",
        ),
        Produto(
            nome="MSI MAG B650 Tomahawk WiFi", marca="MSI",
            categoria_id=cat("motherboard").id, socket="AM5", tipo_ram="DDR5",
            consumo_watts=42,
            descricao="Socket AM5 | DDR5 (4x DIMM, até 128GB) | WiFi 6E | Bluetooth 5.3 | PCIe 5.0 x16 | 2x M.2 (1x PCIe 5.0) | USB 3.2 Gen 2x2 | ATX | Fase de energia robusta para Ryzen 7000.",
            imagem_url="https://www.pcworld.com/wp-content/uploads/2025/04/Screenshot-2022-11-28-at-1.15.48-PM.png",
        ),
        Produto(
            nome="Gigabyte B550M AORUS Elite", marca="Gigabyte",
            categoria_id=cat("motherboard").id, socket="AM4", tipo_ram="DDR4",
            consumo_watts=30,
            descricao="Socket AM4 | DDR4 (4x DIMM, até 128GB) | PCIe 4.0 x16 | 2x M.2 NVMe | USB 3.2 Gen 2 | Realtek 2.5G LAN | mATX | Placa completa AM4 DDR4 com PCIe 4.0.",
            imagem_url="https://imgs.pontofrio.com.br/1559023148/1xg.jpg?imwidth=1000",
        ),
        Produto(
            nome="ASUS ROG Strix B550-F Gaming WiFi", marca="ASUS",
            categoria_id=cat("motherboard").id, socket="AM4", tipo_ram="DDR4",
            consumo_watts=35,
            descricao="Socket AM4 | DDR4 (4x DIMM, até 128GB) | WiFi 6 | Bluetooth 5.0 | PCIe 4.0 x16 | 2x M.2 NVMe | USB 3.2 Gen 2 | ATX | Estética premium ROG com fases de energia reforçadas.",
            imagem_url="https://img.terabyteshop.com.br/archive/1899670914/13980-rog-strix-b550-f-gaming-wifi-06.png",
        ),
        Produto(
            nome="MSI PRO B760M-A WiFi DDR4", marca="MSI",
            categoria_id=cat("motherboard").id, socket="LGA1700", tipo_ram="DDR4",
            consumo_watts=28,
            descricao="Socket LGA1700 | DDR4 (4x DIMM, até 128GB) | WiFi 6E | Bluetooth 5.3 | PCIe 4.0 x16 | 2x M.2 NVMe | 2.5G LAN | mATX | Placa acessível LGA1700 DDR4.",
            imagem_url="https://hyperpc.ae/images/catalog/hardware/motherboards/1700/msi/pro-b760m-a/msi-pro-b760m-awifi.jpg?mtime=1679308780",
        ),
        Produto(
            nome="ASUS Prime Z790-P WiFi DDR5", marca="ASUS",
            categoria_id=cat("motherboard").id, socket="LGA1700", tipo_ram="DDR5",
            consumo_watts=45,
            descricao="Socket LGA1700 | DDR5 (4x DIMM, até 128GB) | WiFi 6E | Bluetooth 5.3 | PCIe 5.0 x16 | 3x M.2 NVMe (1x PCIe 5.0) | USB 3.2 Gen 2x2 | ATX | Chipset Z790 com bom suporte a DDR5.",
            imagem_url="https://m.media-amazon.com/images/S/aplus-media-library-service-media/74ca7f1a-414c-4010-8b4a-021a5429f62a.__CR0,0,300,300_PT0_SX300_V1___.png",
        ),
        Produto(
            nome="MSI MAG B550 Tomahawk", marca="MSI",
            categoria_id=cat("motherboard").id, socket="AM4", tipo_ram="DDR4",
            consumo_watts=32,
            descricao="Socket AM4 | DDR4 (4x DIMM, até 128GB) | PCIe 4.0 x16 | 2x M.2 NVMe | Realtek 2.5G LAN | USB 3.2 Gen 2 | ATX | Uma das placas AM4 mais recomendadas — robusta e confiável.",
            imagem_url="https://storage-asset.msi.com/global/picture/image/feature/mb/B550/MAG/TOMAHAWK/B550-TOMAHAWK-storage-overview.jpg",
        ),
        Produto(
            nome="Gigabyte Z790 AORUS Elite AX DDR5", marca="Gigabyte",
            categoria_id=cat("motherboard").id, socket="LGA1700", tipo_ram="DDR5",
            consumo_watts=50,
            descricao="Socket LGA1700 | DDR5 (4x DIMM, até 192GB) | WiFi 6E | Bluetooth 5.3 | PCIe 5.0 x16 | 4x M.2 NVMe | Thunderbolt 4 | USB 3.2 Gen 2x2 | ATX | High-end Intel completo.",
            imagem_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQTKUTwOiD9bvpj9eN6XUU6nt1RC17XVPRvQ&s",
        ),
        Produto(
            nome="ASRock B760M Steel Legend DDR5", marca="ASRock",
            categoria_id=cat("motherboard").id, socket="LGA1700", tipo_ram="DDR5",
            consumo_watts=30,
            descricao="Socket LGA1700 | DDR5 (4x DIMM, até 192GB) | 2.5G LAN | PCIe 4.0 x16 | 2x M.2 NVMe | USB 3.2 Gen 2 | mATX | Custo-benefício DDR5 Intel — compacta e com boa qualidade de VRM.",
            imagem_url="https://www.asrock.com/mb/features/POLYRGBLED-B760M%20Steel%20Legend%20WiFi_mobile.png",
        ),
        Produto(
            nome="ASUS TUF Gaming B550M-Plus WiFi", marca="ASUS",
            categoria_id=cat("motherboard").id, socket="AM4", tipo_ram="DDR4",
            consumo_watts=30,
            descricao="Socket AM4 | DDR4 (4x DIMM, até 128GB) | WiFi 6 | Bluetooth 5.0 | PCIe 4.0 x16 | 2x M.2 NVMe | USB 3.2 Gen 2 | mATX | Tamanho compacto com WiFi integrado.",
            imagem_url="https://www.promoinfo.com.br/img/anuncios/328626.jpg",
        ),

        # ── Storage ───────────────────────────────────────────────
        Produto(
            nome="Samsung 990 Pro NVMe 2TB", marca="Samsung",
            categoria_id=cat("storage").id, capacidade="2TB", consumo_watts=7,
            descricao="2TB | NVMe M.2 PCIe 4.0 x4 | Leitura: 7.450 MB/s | Escrita: 6.900 MB/s | TLC V-NAND | DRAM Cache | 1.200 TBW | Um dos SSDs PCIe 4.0 mais rápidos do mercado.",
            imagem_url="https://theoverclockingpage.com/wp-content/uploads/2023/06/Usuarios_SSD_990_Pro_Samsung_degradacao_rapida-1000x562.jpg",
        ),
        Produto(
            nome="Kingston NV2 NVMe 1TB", marca="Kingston",
            categoria_id=cat("storage").id, capacidade="1TB", consumo_watts=3,
            descricao="1TB | NVMe M.2 PCIe 4.0 x4 | Leitura: 3.500 MB/s | Escrita: 2.100 MB/s | QLC NAND | Sem DRAM (HMB) | 320 TBW | SSD PCIe 4.0 de entrada com ótimo custo.",
            imagem_url="https://http2.mlstatic.com/D_NQ_NP_633719-CBT96978006471_112025-O.webp",
        ),
        Produto(
            nome="WD Black SN850X NVMe 1TB", marca="Western Digital",
            categoria_id=cat("storage").id, capacidade="1TB", consumo_watts=6,
            descricao="1TB | NVMe M.2 PCIe 4.0 x4 | Leitura: 7.300 MB/s | Escrita: 6.300 MB/s | TLC NAND | DRAM Cache | 600 TBW | Otimizado para gaming — compatível com PS5.",
            imagem_url="https://i0.wp.com/theoverclockingpage.com/wp-content/uploads/2024/09/YT-top.webp",
        ),
        Produto(
            nome="Seagate Barracuda HDD 2TB", marca="Seagate",
            categoria_id=cat("storage").id, capacidade="2TB", consumo_watts=9,
            descricao="2TB | 3.5\" SATA 6Gb/s | 7.200 RPM | Cache 256MB | Ideal para armazenamento massivo de jogos, filmes e backups. Alta capacidade a custo acessível.",
            imagem_url="https://images.kabum.com.br/produtos/fotos/sync_mirakl/1037878/xlarge/Hd-Seagate-Barracuda-2TB-3-5-Sata-7200rpm-Desktop-pc_1778778234.png",
        ),
        Produto(
            nome="Samsung 870 EVO SSD 1TB", marca="Samsung",
            categoria_id=cat("storage").id, capacidade="1TB", consumo_watts=4,
            descricao="1TB | SATA 6Gb/s | Leitura: 560 MB/s | Escrita: 530 MB/s | MLC V-NAND | DRAM Cache | 600 TBW | Melhor SSD SATA do mercado — confiável para upgrade de notebooks e desktops.",
            imagem_url="https://http2.mlstatic.com/D_NQ_NP_825698-MLB85127113655_052025-O.webp",
        ),
        Produto(
            nome="Crucial P3 Plus NVMe 2TB", marca="Crucial",
            categoria_id=cat("storage").id, capacidade="2TB", consumo_watts=4,
            descricao="2TB | NVMe M.2 PCIe 4.0 x4 | Leitura: 5.000 MB/s | Escrita: 4.200 MB/s | QLC NAND | Sem DRAM (HMB) | 440 TBW | Ótimo custo por GB — 2TB PCIe 4.0 acessível.",
            imagem_url="https://http2.mlstatic.com/D_NQ_NP_719859-MLA84474291873_052025-O.webp",
        ),
        Produto(
            nome="WD Blue SN580 NVMe 500GB", marca="Western Digital",
            categoria_id=cat("storage").id, capacidade="500GB", consumo_watts=3,
            descricao="500GB | NVMe M.2 PCIe 4.0 x4 | Leitura: 4.150 MB/s | Escrita: 3.600 MB/s | TLC NAND | Sem DRAM (HMB) | 300 TBW | SSD compacto e rápido — ideal como disco do SO.",
            imagem_url="https://img.terabyteshop.com.br/archive/3734298550/html%202.jpg",
        ),
        Produto(
            nome="Samsung 990 Pro NVMe 1TB", marca="Samsung",
            categoria_id=cat("storage").id, capacidade="1TB", consumo_watts=6,
            descricao="1TB | NVMe M.2 PCIe 4.0 x4 | Leitura: 7.450 MB/s | Escrita: 6.900 MB/s | TLC V-NAND | DRAM Cache | 600 TBW | Velocidade máxima PCIe 4.0 com latências de classe mundial.",
            imagem_url="https://images.samsung.com/is/image/samsung/p6pim/sg/feature/others/sg-feature-990pro-nvme-m2-ssd-551901139?$FB_TYPE_I_JPG$",
        ),
        Produto(
            nome="Kingston KC3000 NVMe 2TB", marca="Kingston",
            categoria_id=cat("storage").id, capacidade="2TB", consumo_watts=9,
            descricao="2TB | NVMe M.2 PCIe 4.0 x4 | Leitura: 7.000 MB/s | Escrita: 7.000 MB/s | TLC NAND | DRAM Cache | 1.600 TBW | High-end Kingston — altíssima resistência para workstations.",
            imagem_url="https://m.media-amazon.com/images/S/aplus-media-library-service-media/0933918a-64f8-47d4-bdd5-1653caa6d504.__CR92,0,1015,628_PT0_SX970_V1___.jpg",
        ),
        Produto(
            nome="Seagate FireCuda 530 NVMe 1TB", marca="Seagate",
            categoria_id=cat("storage").id, capacidade="1TB", consumo_watts=7,
            descricao="1TB | NVMe M.2 PCIe 4.0 x4 | Leitura: 7.300 MB/s | Escrita: 6.900 MB/s | TLC NAND | DRAM Cache | 1.275 TBW | Compatível com PS5 | Garantia de 5 anos.",
            imagem_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRtGfXIN7G-vDVvBHutMBGFqm-hHBBIbdyqg&s",
        ),

        # ── Fontes ────────────────────────────────────────────────
        Produto(
            nome="Corsair RM850x 850W 80+ Gold", marca="Corsair",
            categoria_id=cat("psu").id, consumo_watts=850,
            descricao="850W | 80+ Gold | Full Modular | Ventilador 135mm Zero RPM | ATX 3.0 | Conector PCIe 5.0 12VHPWR | Cabo flat | Uma das fontes mais recomendadas do mercado.",
            imagem_url="https://m.media-amazon.com/images/I/81gxHU2qTSL.jpg",
        ),
        Produto(
            nome="Seasonic Focus GX-750 750W 80+ Gold", marca="Seasonic",
            categoria_id=cat("psu").id, consumo_watts=750,
            descricao="750W | 80+ Gold | Full Modular | Ventilador 120mm Fluid Dynamic | ATX | Capacitor japonês | Garantia 10 anos | Tier S — uma das melhores fontes pelo custo.",
            imagem_url="https://img.terabyteshop.com.br/archive/4134167733/02.png",
        ),
        Produto(
            nome="be quiet! Straight Power 11 650W 80+ Gold", marca="be quiet!",
            categoria_id=cat("psu").id, consumo_watts=650,
            descricao="650W | 80+ Gold | Full Modular | Ventilador 135mm Silent Wings | Regulação DC-DC | Cabos flat | Silenciosa extremamente | Ideal para builds que precisam de máximo silêncio.",
            imagem_url="https://m.media-amazon.com/images/S/aplus-media/vc/54f281e5-56ae-42c1-81d7-f1fdb53bec0c.__CR0,0,300,300_PT0_SX300_V1___.jpg",
        ),
        Produto(
            nome="EVGA SuperNOVA 850 G6 850W 80+ Gold", marca="EVGA",
            categoria_id=cat("psu").id, consumo_watts=850,
            descricao="850W | 80+ Gold | Full Modular | Ventilador FDB 135mm | ATX 3.0 | Conector 12VHPWR | Ripple < 40mV | Fonte robusta e confiável para GPUs de nova geração.",
            imagem_url="https://images10.newegg.com/BizIntell/item/17/438/17-438-212/EVGA%20Power%20Supply-220-G6-0850-X1-a1.jpg",
        ),
        Produto(
            nome="Corsair CV650 650W 80+ Bronze", marca="Corsair",
            categoria_id=cat("psu").id, consumo_watts=650,
            descricao="650W | 80+ Bronze | Semi Modular | Ventilador 120mm | ATX | Proteções OVP/OCP/SCP/OPP | Fonte de entrada confiável da Corsair para builds de custo controlado.",
            imagem_url="https://makeshop-multi-images.akamaized.net/owldirect/shopimages/41/26/1_000000002641.jpg",
        ),
        Produto(
            nome="Cooler Master MWE Gold 750W 80+ Gold", marca="Cooler Master",
            categoria_id=cat("psu").id, consumo_watts=750,
            descricao="750W | 80+ Gold | Full Modular | Ventilador 120mm | ATX | Capacitores japoneses 105°C | Excelente custo-benefício — fonte modular Gold de marca reconhecida.",
            imagem_url="https://a.storyblok.com/f/281110/62d750318d/0829_30.png",
        ),
        Produto(
            nome="Seasonic Focus PX-1000 1000W 80+ Platinum", marca="Seasonic",
            categoria_id=cat("psu").id, consumo_watts=1000,
            descricao="1000W | 80+ Platinum | Full Modular | Ventilador 120mm modo fanless | ATX 3.0 | Conector 12VHPWR | Garantia 12 anos | Tier S para builds com RTX 5080/5090.",
            imagem_url="https://m.media-amazon.com/images/I/81B4R70DViL._AC_UF350,350_QL80_.jpg",
        ),
        Produto(
            nome="Lian Li SP750 750W 80+ Gold SFX", marca="Lian Li",
            categoria_id=cat("psu").id, consumo_watts=750,
            descricao="750W | 80+ Gold | Formato SFX | Full Modular | Ventilador 92mm | Inclui bracket ATX | A melhor fonte SFX para builds ITX — compacta sem abrir mão da potência.",
            imagem_url="https://m.media-amazon.com/images/I/81B4R70DViL._AC_UF350,350_QL80_.jpg",
        ),
        Produto(
            nome="DeepCool PQ650M 650W 80+ Gold", marca="DeepCool",
            categoria_id=cat("psu").id, consumo_watts=650,
            descricao="650W | 80+ Gold | Semi Modular | Ventilador 120mm | Proteções completas | Garantia 5 anos | Opção custo-benefício na faixa Gold para builds mid-range.",
            imagem_url="https://img.terabyteshop.com.br/archive/1452990473/HTML%202.jpg",
        ),
        Produto(
            nome="Corsair HX1500i 1500W 80+ Platinum", marca="Corsair",
            categoria_id=cat("psu").id, consumo_watts=1500,
            descricao="1500W | 80+ Platinum | Full Modular | ATX 3.0 | Conector 12VHPWR | iCUE monitoramento digital | Zero RPM a carga baixa | Para workstations extremas e setups com RTX 5090.",
            imagem_url="https://5.imimg.com/data5/SELLER/Default/2025/1/479589881/SP/BJ/QG/236766879/corsair-hx1500i-1500-watt-atx-3-0-80-plus-platinum-smps-250x250.jpg",
        ),

        # ── Gabinetes ─────────────────────────────────────────────
        Produto(
            nome="Lian Li Lancool 216 RGB", marca="Lian Li",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX/ITX | 2x Fan 160mm RGB incluso | Suporte até 420mm GPU | Vidro temperado lateral | Airflow de classe mundial — um dos mais recomendados do mercado.",
            imagem_url="https://files.gamingpc.com.ua/image/cache/425x372-crop/131dae98dcbf3feaa13fee4d719a4156.webp",
        ),
        Produto(
            nome="Fractal Design Meshify 2", marca="Fractal Design",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX/ITX | 3x Fan 140mm incluso | Painel frontal mesh de alta permeabilidade | Suporte a radiadores de 360mm | Design minimalista escandinavo.",
            imagem_url="https://pcper.com/wp-content/uploads/2020/11/p1020183.jpg",
        ),
        Produto(
            nome="Phanteks Eclipse G360A", marca="Phanteks",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX | 3x Fan 120mm incluso | Painel frontal e lateral com mesh | Vidro temperado | Excelente airflow a preço competitivo.",
            imagem_url="https://lytetechnology.com/wp-content/uploads/2022/05/Phanteks-Eclipse-P360A-Black-300x300.png",
        ),
        Produto(
            nome="NZXT H7 Flow RGB", marca="NZXT",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX/ITX | 4x Fan 120mm RGB incluso | Painel frontal perfurado | Vidro temperado | Gerenciamento de cabos | Design limpo e elegante com bom fluxo de ar.",
            imagem_url="https://nzxt.com/cdn/shop/files/h7-flow-rgb-hero-black_1.png?v=1744876437&width=2000",
        ),
        Produto(
            nome="Corsair 4000D Airflow", marca="Corsair",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX/ITX | 2x Fan 120mm incluso | Frontal airflow perfurado | Vidro temperado | Um dos gabinetes mais vendidos — excelente airflow e organização de cabos.",
            imagem_url="https://res.cloudinary.com/corsair-pwa/image/upload/w_256,h_256,c_pad,q_auto:best/products/Cases/base-4000d-airflow-config/Gallery/4000D_AF_BLACK_01.png",
        ),
        Produto(
            nome="Lian Li O11 Dynamic EVO", marca="Lian Li",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid/Full Tower | ATX/mATX/ITX/E-ATX | Vidro duplo (lateral e frente) | Suporte a watercooling completo | 3x slots USB-C | Favorito de builds premium.",
            imagem_url="https://hyperpc.ae/images/catalog/hardware/cases/lian-li/dynamic-evo-rgb/lian-li-dynamic-evo-rgb-black.jpg?mtime=1776702011",
        ),
        Produto(
            nome="Cooler Master MasterBox TD500 Mesh", marca="Cooler Master",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX | 3x Fan 120mm ARGB incluso | Frontal mesh 3D | Vidro temperado | Visual agressivo e boa ventilação — popular em builds com RGB.",
            imagem_url="https://i0.wp.com/computerage.lk/wp-content/uploads/2025/03/COOLER-MASTER-MASTERBOX-TD500-MESH-V2-CASE.jpg?fit=2100%2C2077&ssl=1",
        ),
        Produto(
            nome="Fractal Design North", marca="Fractal Design",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX/ITX | 2x Fan 140mm incluso | Frente em madeira e lateral mesh | Design escandinavo único | Combina estética premium com bom desempenho térmico.",
            imagem_url="https://hyperpc.ae/images/catalog/hardware/cases/fractal-design/design-north/fractal-design-north-charcoal.jpg?mtime=1718860438",
        ),
        Produto(
            nome="be quiet! Silent Base 802", marca="be quiet!",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid/Full Tower | ATX/mATX/E-ATX | 3x Fan 140mm Pure Wings incluso | Painéis insonorizados | Modular — pode remover frente/tampo | O gabinete mais silencioso para builds focadas em baixo ruído.",
            imagem_url="https://www.bequiet.com/admin/ImageServer.php?ID=1918ba34431@be-quiet.net&omitPreview=true&width=1200",
        ),
        Produto(
            nome="Redragon Wheel Jack GC-603", marca="Redragon",
            categoria_id=cat("case").id, consumo_watts=0,
            descricao="Mid Tower | ATX/mATX | Vidro acrílico lateral | Suporte a GPU até 380mm | 1x Fan 120mm incluso | Gabinete de entrada acessível — boa relação custo-benefício para primeiras builds.",
            imagem_url="https://images.oficinadosbits.com.br/images_storage/25807_02.jpg",
        ),

        # ── Coolers ───────────────────────────────────────────────
        Produto(
            nome="Noctua NH-D15 chromax.black", marca="Noctua",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="Torre dupla | 2x Fan NF-A15 140mm | TDP: 250W+ | AM4/AM5/LGA1700/LGA1200 | Altura: 165mm | O melhor air cooler do mercado — vence muitos AIOs de 240mm.",
            imagem_url="https://pcunboxing.com/wp-content/uploads/NH-D15-G2-chromax.black-46.jpg",
        ),
        Produto(
            nome="be quiet! Dark Rock Pro 4", marca="be quiet!",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="Torre dupla | 2x Fan 120/135mm Silent Wings | TDP: 250W | AM4/AM5/LGA1700 | Altura: 163mm | 4x heatpipes de cobre | Silencioso e potente — rival direto do NH-D15.",
            imagem_url="https://static.tweaktown.com/content/1x1/8842_quiet-dark-rock-pro-4-cpu-cooler-review.jpg",
        ),
        Produto(
            nome="DeepCool AK620", marca="DeepCool",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="Torre dupla | 2x Fan 120mm | TDP: 260W | AM4/AM5/LGA1700 | Altura: 160mm | 6x heatpipes de cobre | Excelente custo-benefício — desempenho próximo ao NH-D15 por menos.",
            imagem_url="https://cdn.deepcool.com/public/ProductFile/DEEPCOOL/Cooling/CPUAirCoolers/AK620_DIGITAL/Gallery/800X800/02.jpg?fm=webp&q=60",
        ),
        Produto(
            nome="ARCTIC Liquid Freezer III 360 AIO", marca="ARCTIC",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="AIO Watercooling | Radiador 360mm | 3x Fan 120mm | TDP: 400W+ | AM4/AM5/LGA1700/LGA1200 | Bomba ultra-silenciosa | Melhor AIO 360mm custo-benefício.",
            imagem_url="https://www.arctic.de/media/04/54/13/1742566976/LFIII_Pro_Black_360.jpg",
        ),
        Produto(
            nome="Corsair iCUE H150i Elite LCD 360 AIO", marca="Corsair",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="AIO Watercooling | Radiador 360mm | 3x Fan 120mm | TDP: 300W+ | Display LCD 2.1\" na bomba | RGB | iCUE software | AIO premium com display customizável.",
            imagem_url="https://img.terabyteshop.com.br/archive/2335137020/550%204.jpg",
        ),
        Produto(
            nome="Noctua NH-U12S redux", marca="Noctua",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="Torre simples | 1x Fan NF-P12 120mm | TDP: 150W | AM4/AM5/LGA1700 | Altura: 158mm | Compacto, silencioso e confiável — ideal para gabinetes com restrição de altura.",
            imagem_url="https://aphnetworks.com/article_images/reviews/noctua-nh-u12s-redux/004.jpg",
        ),
        Produto(
            nome="ID-Cooling SE-226-XT 120mm", marca="ID-Cooling",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="Torre simples | 1x Fan 120mm | TDP: 200W | AM4/AM5/LGA1700 | Altura: 155mm | 6x heatpipes | Melhor air cooler de custo ultra-baixo — supera facilmente soluções stock.",
            imagem_url="https://static.idcooling.com/file/image/20210901/20210901095252_18395.jpg",
        ),
        Produto(
            nome="Thermalright Peerless Assassin 120 SE", marca="Thermalright",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="Torre dupla | 2x Fan 120mm | TDP: 280W | AM4/AM5/LGA1700 | Altura: 155mm | 6x heatpipes | Surpreendente desempenho a preço acessível — favorito dos builds custo-benefício.",
            imagem_url="https://m.media-amazon.com/images/I/71nfuJkieZL.jpg",
        ),
        Produto(
            nome="ASUS ROG Ryujin III 360 AIO", marca="ASUS",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="AIO Watercooling | Radiador 360mm | 3x Fan 120mm ROG | TDP: 350W+ | Display OLED 3.5\" na bomba | RGB Aura Sync | AIO flagship ASUS — integração perfeita com o ecossistema ROG.",
            imagem_url="https://root-nation.com/wp-content/uploads/2023/09/asus-rog-ryujin-iii-360-argb-2.jpg",
        ),
        Produto(
            nome="Cooler Master Hyper 212 Black Edition", marca="Cooler Master",
            categoria_id=cat("cooler").id, consumo_watts=0,
            descricao="Torre simples | 1x Fan 120mm | TDP: 150W | AM4/AM5/LGA1700/LGA1200 | Altura: 158mm | 4x heatpipes | Ícone do mercado — o cooler mais vendido da história, confiável e acessível.",
            imagem_url="https://img.pccasegear.com/images/RR-212S-20PK-R2-ftr5.jpg",
        ),
    ]

    for p in produtos:
        if not Produto.query.filter_by(nome=p.nome).first():
            db.session.add(p)
    db.session.flush()

    # ── Lojas ─────────────────────────────────────────────────────
    lojas_data = [
        Loja(nome="KaBuM!",       url="https://kabum.com.br"),
        Loja(nome="Amazon BR",    url="https://amazon.com.br"),
        Loja(nome="Pichau",       url="https://pichau.com.br"),
        Loja(nome="TerabyteShop", url="https://terabyteshop.com.br"),
    ]
    for l in lojas_data:
        if not Loja.query.filter_by(nome=l.nome).first():
            db.session.add(l)
    db.session.flush()

    def loja(nome): return Loja.query.filter_by(nome=nome).first()
    def prod(nome): return Produto.query.filter_by(nome=nome).first()

    precos_data = [
        # CPUs
        ("AMD Ryzen 5 5600",            "KaBuM!",       579.90),
        ("AMD Ryzen 5 5600",            "Pichau",        569.90),
        ("AMD Ryzen 5 5600",            "Amazon BR",     599.00),
        ("AMD Ryzen 5 5600",            "TerabyteShop",  589.90),
        ("AMD Ryzen 7 7700X",           "KaBuM!",       1099.90),
        ("AMD Ryzen 7 7700X",           "Pichau",       1079.90),
        ("AMD Ryzen 7 7700X",           "Amazon BR",    1149.00),
        ("AMD Ryzen 5 7600X",           "KaBuM!",        929.99),
        ("AMD Ryzen 5 7600X",           "Pichau",        909.90),
        ("AMD Ryzen 5 7600X",           "Amazon BR",     999.00),
        ("Intel Core i5-13600K",        "KaBuM!",       1349.90),
        ("Intel Core i5-13600K",        "Pichau",       1329.90),
        ("Intel Core i5-13600K",        "Amazon BR",    1399.00),
        ("Intel Core i5-13600K",        "TerabyteShop", 1369.90),
        ("Intel Core i7-14700K",        "KaBuM!",       2499.99),
        ("Intel Core i7-14700K",        "Pichau",       2449.90),
        ("Intel Core i7-14700K",        "Amazon BR",    2536.00),
        ("Intel Core i3-12100F",        "KaBuM!",        479.90),
        ("Intel Core i3-12100F",        "Pichau",        499.99),
        ("Intel Core i3-12100F",        "Amazon BR",     519.00),
        ("AMD Ryzen 9 7900X",           "KaBuM!",       2259.99),
        ("AMD Ryzen 9 7900X",           "Pichau",       2199.90),
        ("AMD Ryzen 9 7900X",           "Amazon BR",    2482.34),
        ("AMD Ryzen 5 5500",            "KaBuM!",        399.90),
        ("AMD Ryzen 5 5500",            "Pichau",        389.90),
        ("AMD Ryzen 5 5500",            "Amazon BR",     419.00),
        ("Intel Core i9-14900K",        "KaBuM!",       2999.99),
        ("Intel Core i9-14900K",        "Pichau",       2899.99),
        ("Intel Core i9-14900K",        "Amazon BR",    3950.00),
        ("AMD Ryzen 7 5700X",           "KaBuM!",        699.90),
        ("AMD Ryzen 7 5700X",           "Pichau",        679.90),
        ("AMD Ryzen 7 5700X",           "Amazon BR",     749.00),
        # GPUs
        ("NVIDIA RTX 5090",             "Pichau",       25999.99),
        ("NVIDIA RTX 5090",             "KaBuM!",       26499.00),
        ("NVIDIA RTX 5080",             "Pichau",       10899.98),
        ("NVIDIA RTX 5080",             "KaBuM!",       11299.00),
        ("NVIDIA RTX 5070 Ti",          "Pichau",        7599.99),
        ("NVIDIA RTX 5070 Ti",          "KaBuM!",        7899.00),
        ("NVIDIA RTX 5060 Ti",          "Pichau",        2999.99),
        ("NVIDIA RTX 5060 Ti",          "KaBuM!",        3149.00),
        ("NVIDIA RTX 5060 Ti",          "Amazon BR",     3299.00),
        ("NVIDIA RTX 4070",             "KaBuM!",        3499.90),
        ("NVIDIA RTX 4070",             "Pichau",        3399.90),
        ("NVIDIA RTX 4070",             "Amazon BR",     3699.00),
        ("NVIDIA RTX 4060",             "KaBuM!",        1999.90),
        ("NVIDIA RTX 4060",             "Pichau",        1979.90),
        ("NVIDIA RTX 4060",             "Amazon BR",     2049.00),
        ("NVIDIA RTX 3060 12GB",        "KaBuM!",        1549.90),
        ("NVIDIA RTX 3060 12GB",        "Pichau",        2159.99),
        ("NVIDIA RTX 3060 12GB",        "Amazon BR",     1699.00),
        ("AMD Radeon RX 7800 XT",       "KaBuM!",        3099.90),
        ("AMD Radeon RX 7800 XT",       "Pichau",        2999.90),
        ("AMD Radeon RX 7800 XT",       "Amazon BR",     3299.00),
        ("AMD Radeon RX 7600",          "KaBuM!",        1599.90),
        ("AMD Radeon RX 7600",          "Pichau",        1549.90),
        ("AMD Radeon RX 7600",          "Amazon BR",     1699.00),
        ("NVIDIA RTX 3050",             "KaBuM!",        1149.90),
        ("NVIDIA RTX 3050",             "Pichau",        1349.99),
        ("NVIDIA RTX 3050",             "Amazon BR",     1299.00),
        # RAM
        ("Kingston FURY Beast 32GB DDR5 6000MHz",     "KaBuM!",      699.90),
        ("Kingston FURY Beast 32GB DDR5 6000MHz",     "Pichau",      679.90),
        ("Kingston FURY Beast 32GB DDR5 6000MHz",     "Amazon BR",   729.00),
        ("Corsair Vengeance 32GB DDR5 5600MHz",       "KaBuM!",      649.90),
        ("Corsair Vengeance 32GB DDR5 5600MHz",       "Pichau",      629.90),
        ("Corsair Vengeance 32GB DDR5 5600MHz",       "Amazon BR",   679.00),
        ("G.Skill Trident Z5 32GB DDR5 6400MHz",      "KaBuM!",      849.90),
        ("G.Skill Trident Z5 32GB DDR5 6400MHz",      "Pichau",      819.90),
        ("G.Skill Trident Z5 32GB DDR5 6400MHz",      "Amazon BR",   899.00),
        ("Kingston FURY Beast 16GB DDR4 3200MHz",     "KaBuM!",      219.90),
        ("Kingston FURY Beast 16GB DDR4 3200MHz",     "Pichau",      209.90),
        ("Kingston FURY Beast 16GB DDR4 3200MHz",     "Amazon BR",   239.00),
        ("Corsair Vengeance LPX 16GB DDR4 3600MHz",   "KaBuM!",      249.90),
        ("Corsair Vengeance LPX 16GB DDR4 3600MHz",   "Pichau",      239.90),
        ("Corsair Vengeance LPX 16GB DDR4 3600MHz",   "Amazon BR",   269.00),
        ("G.Skill Ripjaws V 32GB DDR4 3600MHz",       "KaBuM!",      449.90),
        ("G.Skill Ripjaws V 32GB DDR4 3600MHz",       "Pichau",      429.90),
        ("G.Skill Ripjaws V 32GB DDR4 3600MHz",       "Amazon BR",   479.00),
        ("Corsair Vengeance RGB Pro 16GB DDR4 3200MHz","KaBuM!",      299.90),
        ("Corsair Vengeance RGB Pro 16GB DDR4 3200MHz","Pichau",      289.90),
        ("Corsair Vengeance RGB Pro 16GB DDR4 3200MHz","Amazon BR",   319.00),
        ("XPG Lancer 32GB DDR5 6000MHz",              "KaBuM!",      749.90),
        ("XPG Lancer 32GB DDR5 6000MHz",              "Pichau",      729.90),
        ("XPG Lancer 32GB DDR5 6000MHz",              "Amazon BR",   789.00),
        ("Kingston Fury Renegade 32GB DDR5 7200MHz",  "KaBuM!",      999.90),
        ("Kingston Fury Renegade 32GB DDR5 7200MHz",  "Pichau",      979.90),
        ("Kingston Fury Renegade 32GB DDR5 7200MHz",  "Amazon BR",  1049.00),
        ("Crucial 16GB DDR5 4800MHz",                 "KaBuM!",      319.90),
        ("Crucial 16GB DDR5 4800MHz",                 "Pichau",      309.90),
        ("Crucial 16GB DDR5 4800MHz",                 "Amazon BR",   339.00),
        # Motherboards
        ("ASUS TUF Gaming B650-Plus WiFi",        "KaBuM!",      1099.90),
        ("ASUS TUF Gaming B650-Plus WiFi",        "Pichau",      1079.90),
        ("ASUS TUF Gaming B650-Plus WiFi",        "Amazon BR",   1149.00),
        ("MSI MAG B650 Tomahawk WiFi",            "KaBuM!",      1199.90),
        ("MSI MAG B650 Tomahawk WiFi",            "Pichau",      1179.90),
        ("MSI MAG B650 Tomahawk WiFi",            "Amazon BR",   1249.00),
        ("Gigabyte B550M AORUS Elite",            "KaBuM!",       699.90),
        ("Gigabyte B550M AORUS Elite",            "Pichau",       679.90),
        ("Gigabyte B550M AORUS Elite",            "Amazon BR",    729.00),
        ("ASUS ROG Strix B550-F Gaming WiFi",     "KaBuM!",       999.90),
        ("ASUS ROG Strix B550-F Gaming WiFi",     "Pichau",       979.90),
        ("ASUS ROG Strix B550-F Gaming WiFi",     "Amazon BR",   1049.00),
        ("MSI PRO B760M-A WiFi DDR4",             "KaBuM!",       699.90),
        ("MSI PRO B760M-A WiFi DDR4",             "Pichau",       679.90),
        ("MSI PRO B760M-A WiFi DDR4",             "Amazon BR",    729.00),
        ("ASUS Prime Z790-P WiFi DDR5",           "KaBuM!",      1299.90),
        ("ASUS Prime Z790-P WiFi DDR5",           "Pichau",      1269.90),
        ("ASUS Prime Z790-P WiFi DDR5",           "Amazon BR",   1349.00),
        ("MSI MAG B550 Tomahawk",                 "KaBuM!",       799.90),
        ("MSI MAG B550 Tomahawk",                 "Pichau",       779.90),
        ("MSI MAG B550 Tomahawk",                 "Amazon BR",    829.00),
        ("Gigabyte Z790 AORUS Elite AX DDR5",     "KaBuM!",      1999.90),
        ("Gigabyte Z790 AORUS Elite AX DDR5",     "Pichau",      1969.90),
        ("Gigabyte Z790 AORUS Elite AX DDR5",     "Amazon BR",   2099.00),
        ("ASRock B760M Steel Legend DDR5",        "KaBuM!",       699.90),
        ("ASRock B760M Steel Legend DDR5",        "Pichau",       679.90),
        ("ASRock B760M Steel Legend DDR5",        "Amazon BR",    729.00),
        ("ASUS TUF Gaming B550M-Plus WiFi",       "KaBuM!",       799.90),
        ("ASUS TUF Gaming B550M-Plus WiFi",       "Pichau",       779.90),
        ("ASUS TUF Gaming B550M-Plus WiFi",       "Amazon BR",    829.00),
        # Storage
        ("Samsung 990 Pro NVMe 2TB",          "KaBuM!",      749.90),
        ("Samsung 990 Pro NVMe 2TB",          "Pichau",      729.90),
        ("Samsung 990 Pro NVMe 2TB",          "Amazon BR",   799.00),
        ("Kingston NV2 NVMe 1TB",             "KaBuM!",      249.90),
        ("Kingston NV2 NVMe 1TB",             "Pichau",      239.90),
        ("Kingston NV2 NVMe 1TB",             "Amazon BR",   269.00),
        ("WD Black SN850X NVMe 1TB",          "KaBuM!",      529.90),
        ("WD Black SN850X NVMe 1TB",          "Pichau",      509.90),
        ("WD Black SN850X NVMe 1TB",          "Amazon BR",   569.00),
        ("Seagate Barracuda HDD 2TB",         "KaBuM!",      249.90),
        ("Seagate Barracuda HDD 2TB",         "Pichau",      239.90),
        ("Seagate Barracuda HDD 2TB",         "Amazon BR",   269.00),
        ("Samsung 870 EVO SSD 1TB",           "KaBuM!",      399.90),
        ("Samsung 870 EVO SSD 1TB",           "Pichau",      389.90),
        ("Samsung 870 EVO SSD 1TB",           "Amazon BR",   419.00),
        ("Crucial P3 Plus NVMe 2TB",          "KaBuM!",      449.90),
        ("Crucial P3 Plus NVMe 2TB",          "Pichau",      429.90),
        ("Crucial P3 Plus NVMe 2TB",          "Amazon BR",   479.00),
        ("WD Blue SN580 NVMe 500GB",          "KaBuM!",      199.90),
        ("WD Blue SN580 NVMe 500GB",          "Pichau",      189.90),
        ("WD Blue SN580 NVMe 500GB",          "Amazon BR",   219.00),
        ("Samsung 990 Pro NVMe 1TB",          "KaBuM!",      449.90),
        ("Samsung 990 Pro NVMe 1TB",          "Pichau",      429.90),
        ("Samsung 990 Pro NVMe 1TB",          "Amazon BR",   479.00),
        ("Kingston KC3000 NVMe 2TB",          "KaBuM!",      849.90),
        ("Kingston KC3000 NVMe 2TB",          "Pichau",      829.90),
        ("Kingston KC3000 NVMe 2TB",          "Amazon BR",   899.00),
        ("Seagate FireCuda 530 NVMe 1TB",     "KaBuM!",      549.90),
        ("Seagate FireCuda 530 NVMe 1TB",     "Pichau",      529.90),
        ("Seagate FireCuda 530 NVMe 1TB",     "Amazon BR",   579.00),
        # PSUs
        ("Corsair RM850x 850W 80+ Gold",              "KaBuM!",      899.90),
        ("Corsair RM850x 850W 80+ Gold",              "Pichau",      879.90),
        ("Corsair RM850x 850W 80+ Gold",              "Amazon BR",   949.00),
        ("Seasonic Focus GX-750 750W 80+ Gold",       "KaBuM!",      749.90),
        ("Seasonic Focus GX-750 750W 80+ Gold",       "Pichau",      729.90),
        ("Seasonic Focus GX-750 750W 80+ Gold",       "Amazon BR",   799.00),
        ("be quiet! Straight Power 11 650W 80+ Gold", "KaBuM!",      649.90),
        ("be quiet! Straight Power 11 650W 80+ Gold", "Pichau",      629.90),
        ("EVGA SuperNOVA 850 G6 850W 80+ Gold",       "KaBuM!",      849.90),
        ("EVGA SuperNOVA 850 G6 850W 80+ Gold",       "Amazon BR",   899.00),
        ("Corsair CV650 650W 80+ Bronze",             "KaBuM!",      399.90),
        ("Corsair CV650 650W 80+ Bronze",             "Pichau",      389.90),
        ("Corsair CV650 650W 80+ Bronze",             "Amazon BR",   429.00),
        ("Cooler Master MWE Gold 750W 80+ Gold",      "KaBuM!",      549.90),
        ("Cooler Master MWE Gold 750W 80+ Gold",      "Pichau",      529.90),
        ("Cooler Master MWE Gold 750W 80+ Gold",      "Amazon BR",   579.00),
        ("Seasonic Focus PX-1000 1000W 80+ Platinum", "KaBuM!",     1299.90),
        ("Seasonic Focus PX-1000 1000W 80+ Platinum", "Pichau",     1279.90),
        ("Seasonic Focus PX-1000 1000W 80+ Platinum", "Amazon BR",  1349.00),
        ("Lian Li SP750 750W 80+ Gold SFX",           "KaBuM!",      799.90),
        ("Lian Li SP750 750W 80+ Gold SFX",           "Pichau",      779.90),
        ("DeepCool PQ650M 650W 80+ Gold",             "KaBuM!",      449.90),
        ("DeepCool PQ650M 650W 80+ Gold",             "Pichau",      429.90),
        ("DeepCool PQ650M 650W 80+ Gold",             "Amazon BR",   469.00),
        ("Corsair HX1500i 1500W 80+ Platinum",        "KaBuM!",     2199.90),
        ("Corsair HX1500i 1500W 80+ Platinum",        "Pichau",     2149.90),
        ("Corsair HX1500i 1500W 80+ Platinum",        "Amazon BR",  2299.00),
        # Cases
        ("Lian Li Lancool 216 RGB",             "KaBuM!",      699.90),
        ("Lian Li Lancool 216 RGB",             "Pichau",      679.90),
        ("Lian Li Lancool 216 RGB",             "Amazon BR",   729.00),
        ("Fractal Design Meshify 2",            "KaBuM!",      899.90),
        ("Fractal Design Meshify 2",            "Pichau",      879.90),
        ("Fractal Design Meshify 2",            "Amazon BR",   949.00),
        ("Phanteks Eclipse G360A",              "KaBuM!",      549.90),
        ("Phanteks Eclipse G360A",              "Pichau",      529.90),
        ("NZXT H7 Flow RGB",                    "KaBuM!",      899.90),
        ("NZXT H7 Flow RGB",                    "Pichau",      879.90),
        ("NZXT H7 Flow RGB",                    "Amazon BR",   949.00),
        ("Corsair 4000D Airflow",               "KaBuM!",      599.90),
        ("Corsair 4000D Airflow",               "Pichau",      579.90),
        ("Corsair 4000D Airflow",               "Amazon BR",   639.00),
        ("Lian Li O11 Dynamic EVO",             "KaBuM!",     1199.90),
        ("Lian Li O11 Dynamic EVO",             "Pichau",     1179.90),
        ("Lian Li O11 Dynamic EVO",             "Amazon BR",  1249.00),
        ("Cooler Master MasterBox TD500 Mesh",  "KaBuM!",      549.90),
        ("Cooler Master MasterBox TD500 Mesh",  "Pichau",      529.90),
        ("Cooler Master MasterBox TD500 Mesh",  "Amazon BR",   579.00),
        ("Fractal Design North",                "KaBuM!",      849.90),
        ("Fractal Design North",                "Pichau",      829.90),
        ("Fractal Design North",                "Amazon BR",   899.00),
        ("be quiet! Silent Base 802",           "KaBuM!",      999.90),
        ("be quiet! Silent Base 802",           "Pichau",      979.90),
        ("be quiet! Silent Base 802",           "Amazon BR",  1049.00),
        ("Redragon Wheel Jack GC-603",          "KaBuM!",      279.90),
        ("Redragon Wheel Jack GC-603",          "Pichau",      299.90),
        # Coolers
        ("Noctua NH-D15 chromax.black",              "KaBuM!",      699.90),
        ("Noctua NH-D15 chromax.black",              "Pichau",      679.90),
        ("Noctua NH-D15 chromax.black",              "Amazon BR",   749.00),
        ("be quiet! Dark Rock Pro 4",                "KaBuM!",      499.90),
        ("be quiet! Dark Rock Pro 4",                "Pichau",      479.90),
        ("be quiet! Dark Rock Pro 4",                "Amazon BR",   529.00),
        ("DeepCool AK620",                           "KaBuM!",      299.90),
        ("DeepCool AK620",                           "Pichau",      289.90),
        ("DeepCool AK620",                           "Amazon BR",   319.00),
        ("ARCTIC Liquid Freezer III 360 AIO",        "KaBuM!",      599.90),
        ("ARCTIC Liquid Freezer III 360 AIO",        "Pichau",      579.90),
        ("ARCTIC Liquid Freezer III 360 AIO",        "Amazon BR",   639.00),
        ("Corsair iCUE H150i Elite LCD 360 AIO",     "KaBuM!",     1199.90),
        ("Corsair iCUE H150i Elite LCD 360 AIO",     "Pichau",     1179.90),
        ("Corsair iCUE H150i Elite LCD 360 AIO",     "Amazon BR",  1249.00),
        ("Noctua NH-U12S redux",                     "KaBuM!",      299.90),
        ("Noctua NH-U12S redux",                     "Pichau",      289.90),
        ("Noctua NH-U12S redux",                     "Amazon BR",   319.00),
        ("ID-Cooling SE-226-XT 120mm",               "KaBuM!",      149.90),
        ("ID-Cooling SE-226-XT 120mm",               "Pichau",      139.90),
        ("Thermalright Peerless Assassin 120 SE",    "KaBuM!",      199.90),
        ("Thermalright Peerless Assassin 120 SE",    "Pichau",      189.90),
        ("Thermalright Peerless Assassin 120 SE",    "Amazon BR",   219.00),
        ("ASUS ROG Ryujin III 360 AIO",              "KaBuM!",     1599.90),
        ("ASUS ROG Ryujin III 360 AIO",              "Pichau",     1549.90),
        ("ASUS ROG Ryujin III 360 AIO",              "Amazon BR",  1699.00),
        ("Cooler Master Hyper 212 Black Edition",    "KaBuM!",      199.90),
        ("Cooler Master Hyper 212 Black Edition",    "Pichau",      189.90),
        ("Cooler Master Hyper 212 Black Edition",    "Amazon BR",   219.00),
        ("Cooler Master Hyper 212 Black Edition",    "TerabyteShop",209.90),
    ]

    for nome_prod, nome_loja, preco_val in precos_data:
        p_obj = prod(nome_prod)
        l_obj = loja(nome_loja)
        if p_obj and l_obj:
            if not Preco.query.filter_by(produto_id=p_obj.id, loja_id=l_obj.id).first():
                db.session.add(Preco(produto_id=p_obj.id, loja_id=l_obj.id, preco=preco_val))

    if not User.query.filter_by(email="admin@setupmaker.com").first():
        admin = User(username="admin", email="admin@setupmaker.com", is_admin=True, email_verificado=True)
        admin.set_password("Admin@123")
        db.session.add(admin)

    db.session.commit()
    print("✅ Seed concluído! 80 produtos em 8 categorias com imagens individuais.")